### 회원가입
POST http://localhost:8080/signup
Content-Type: application/json
Accept: */*

{
  "userId": "user02",
  "userPass": "pass02",
  "userName": "판다",
  "userEmail": "panda@ohgiraffers.com",
  "role": "ADMIN"
}

### 로그인 (비밀번호 포함하기 때문에 post 방식으로 보낸다.)
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "id": "user02",
  "pass": "pass02"
}

### GET 요청
GET http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE4MDA0OTIxMzc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJSb2xlIjoiQURNSU4iLCJzdWIiOiJvaGdpcmFmZmVycyB0b2tlbjEiLCJ1c2VyTmFtZSI6Iu2MkOuLpCIsImV4cCI6MTcxODA5MTMyMX0.nlgTZ78OW9p822O6zVMgv3lk9MSHMWVyfmsfHlfuagk

### POST 요청
POST http://localhost:8080/test
Content-Type: application/json
Accept: */*
Authorization: BEARER eyJkYXRlIjoxNzE4MDA0OTIxMzc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJSb2xlIjoiQURNSU4iLCJzdWIiOiJvaGdpcmFmZmVycyB0b2tlbjEiLCJ1c2VyTmFtZSI6Iu2MkOuLpCIsImV4cCI6MTcxODA5MTMyMX0.nlgTZ78OW9p822O6zVMgv3lk9MSHMWVyfmsfHlfuagk

